version: '3'

services:
  node-app:
    ports:
      - 3000:80
    
    build:
      context: .
      args:
        NODE_ENV: development

    volumes:
      - ./:/app
      - /app/node_modules
    
    environment:
      - NODE_ENV=development
    command: npm run dev