version: '3'

services:
  node-app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - redis
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db: